name: Blank Issue
description: Create a blank issue for discussion
body:  
  - type: markdown
    attributes:
      value: |
        ## 2.0 is released! new repo is [HERE](https://github.com/PDFMathTranslate/PDFMathTranslate-next)
  - type: checkboxes
    id: checks
    attributes:
      label: Before you asking
      options:
      - label: I have tried the PDFMathTranslate-next and give feedback in PDFMathTranslate-next
        required: true
  - type: checkboxes
    id: checks
    attributes:
      label: before ...
      options:
      - label: This issue is not about question or bug.
        required: true
  - type: textarea
    id: describe
    attributes:
      label: Add a description